confirmUserSignup:
  handler: src/handlers/confirm-user-signup/handler.handler
  environment:
    USERS_TABLE: !Ref UsersTable
  iamRoleStatements:
    - Effect: "Allow"
      Action: dynamodb:PutItem
      Resource: !GetAtt UsersTable.Arn
