service: appsyncmasterclass-backend
frameworkVersion: "2"

plugins:
  - serverless-appsync-plugin
  - serverless-iam-roles-per-function
  - serverless-export-env

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    USERS_TABLE: !Ref UsersTable

package:
  individually: true

custom:
  appSync:
    - ${file(src/resources/appsync/appsync-api.yml)}
  export-env:
    overwrite: true

resources:
  - ${file(src/resources/cognito/cognito-user-pool.yml)}
  - ${file(src/resources/cognito/cognito-user-pool-client.yml)}

  - ${file(src/resources/dynamodb/users-table.yml)}


functions:
  - ${file(src/handlers/confirm-user-signup/config.yml)}
