service: appsyncmasterclass-backend
frameworkVersion: "2"

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

package:
  exclude:
    - package-lock.json
    - package.json

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

resources:
  - ${file(resources/cognito/cognito-user-pool.yml)}
  - ${file(resources/cognito/cognito-user-pool-client.yml)}
